#pragma once
#include <vector>

#include "KeyEvent.h"

// Polls the Cardputer keyboard matrix and G0 button, emitting semantic
// KeyEvents once per physical key press (no auto-repeat in MVP).
class InputRouter {
 public:
  // Call once per loop after M5Cardputer.update(). Returns the events
  // generated by this frame's state change (usually 0 or 1).
  std::vector<KeyEvent> poll();
};
